/**
 * Stage the core-crypto WASM module into `public/` so Vite serves it from this
 * app's own origin.
 *
 * We cannot deep-import the .wasm from the package: it is not listed in
 * @wireapp/core-crypto's `exports` map. Copying it to `public/` keeps the
 * asset same-origin, which the app's Content-Security-Policy requires, and
 * avoids fetching cryptographic code from a third-party CDN.
 */
import { copyFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// The package exports neither its package.json nor the .wasm, and its exports
// map only declares an "import" condition — so resolve the ESM browser entry
// point and walk to the asset that sits beside it.
const browserEntry = fileURLToPath(import.meta.resolve('@wireapp/core-crypto/browser'));
const source = join(dirname(browserEntry), 'autogenerated/wasm-bindgen/index_bg.wasm');
const destinationDir = join(here, '..', 'public');
const destination = join(destinationDir, 'corecrypto.wasm');

mkdirSync(destinationDir, { recursive: true });
copyFileSync(source, destination);

console.log(`staged core-crypto wasm -> ${destination}`);
